---
title: "P8105_hw4_km3304"
author: "Kaitlin Maciejewski"
date: "10/26/2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(readr)
library(janitor)
library(lubridate)
```

```{r}
# clean pols-month data set

pols_month = read_csv(file = "./fivethirtyeight_datasets/pols-month.csv") %>% 
  clean_names() %>% 
  # change day of month to first day
  mutate(mon = lubridate::floor_date(mon, unit = "month")) %>% 
  separate(mon, into= c("year", "month", "day"), 
           sep = "-", convert = TRUE) %>% 
  arrange(year, month) %>%
  mutate(month = month.name[month]) %>% 
  #recode president data
  mutate (prez_dem = recode(prez_dem, '1' = "dem", '0' = "gop")) %>% 
  mutate (prez_gop = recode(prez_gop, '0' = "dem", '1' = "gop", '2' = "gop")) 

if (pols_month$prez_gop == pols_month$prez_dem){pols_month$president = pols_month$prez_gop} 

# select and arrange information
pols_month <- select(pols_month, -prez_gop, -prez_dem, -day) %>% 
  select(year, month, everything()) 


#clean GDP data set, arrange by year, month, and change month from numeric to names

GDP = read_csv(file = "./fivethirtyeight_datasets/GDP.csv") %>% 
  clean_names() %>% 
  separate(date, into= c("year", "month", "day"), 
           sep = "-", convert = TRUE) %>% 
  arrange(year, month) %>%
  mutate(month = month.name[month])

is.na(GDP) <- GDP == "." # change "." to NA

# merge datasets

data_538 = left_join(pols_month, GDP) 
  
```

```{r}
mean_gdp = data_538 %>%
  filter(!is.na(value)) %>%
  group_by(year) %>%
  mutate(value = as.numeric(value)) %>%
  summarise(mean_value = mean(value))

plot_gdp_over_time = data_538 %>%
  select(year, president) %>%
  unique() %>%
  left_join(mean_gdp, by = 'year') %>%
  filter(!is.na(mean_value))
    
plot_gdp_over_time %>%
  ggplot(aes(y = mean_value, x = year, fill = president)) + 
  geom_col() +
  ylab('Mean GDP')
```

Above, we present a bar graph showing the mean yearly GDP from 1948 to 2015. At a glance, GDP appears to be overall increasing until the late 70s, when GDP appears to become overall decreasing. This pattern appears to hold regardless of the party holding presidential office. 

